### PR TITLE
add versionlock format for dnf

### LINKED ISSUE #150: Rhel/Centos 8 versionlock doesn't work
Seems like the format of the file has changed in Centos 8

I have to configure like so 
yum::versionlock { '1:java-1.8.0-openjdk-headless-1:1.8.0.232.b09-0.el8_0.*':
    ensure => present,
  }

but the line should be

yum::versionlock { 'java-1.8.0-openjdk-headless-1:1.8.0.232.b09-0.el8_0.*':
    ensure => present,
  }

But the module balks at that !

### PR DESCRIPTION
**Pull request by vchepkov**
#### Pull Request (PR) description
adds support for dnf package provider versionlock format 

#### This Pull Request (PR) fixes the following issues
Fixes #150

### CODE REVIEW

**Comment by vchepkov** [comment]
IMHO, I think that resource should be changed to accept attributes: epoch, version, and so on

**Comment by traylenator** [comment]
Some pseudo code.

I'd suggest forcing people to switch the new format for all nodes once they support CentOS8.


Something like:

```puppet
define yum::versionlock (
  Enum['present', 'absent', 'exclude'] $ensure = 'present',
  Optional[version_match]   $version = undef,
  Optional[release_match]   $release = undef,
  arch_match                $arch = 'x86_64',
  Variant[Integer[0],Enum['*']] $epoch   = 0,
) {
  require yum::plugin::versionlock

  case $name {
    # Old World for OS7
    Yum::VersionlockString: {
       # Force folk to migrate with 8
       if versioncmp($facts['os']['release']['major'],'8') >= 0 {
          fail('Migrate yum::versionlock to specify a name (as package name), version, release and epoch as individual parameters')
        }
        if $version or $release {
            fail("If \$version or \$release is set then \$name (\$name) must be a simple package name and not a full versionlock file entry")
        }
        $_versionlock = $pkgname
    }
    # New world for OS7, 8, ...
    Pattern[/([0-9a-zA-Z\._\+%\{\}\*-]+)]: {
       # Check that release and version are actually set.
       if os == 7 {
         $_versionlock = "${epoch}:${name}-${version}-${release}.${arch}
       } else {
         # DNF formamat
         $_versionlock = "${name}-${epoch}:${version}-${release}.${arch}
       }
    }
    default: {
      fail('advise people to use new name, version, releaes, arch syntax')
    }
  }

  $line_prefix = $ensure ? {
    'exclude' => '!',
    default   => '',
  }

  unless $ensure == 'absent' {
    concat::fragment { "yum-versionlock-${name}":
      content => "${line_prefix}${_versionlock}\n",
      target  => $yum::plugin::versionlock::path,
    }
  }
}
````

This would be backwards compatible for 7 and bug fix for 8.

Though as soon as you support 8 you would forced to migrate for 7 and 8 at the same time.

**Comment by traylenator** [comment]
If I can help let me know. I see you already added the new types as comments.

**Comment by vchepkov** [comment]
I incline to re-work it in the matter you suggested. I hesitated, wasn't sure if it would be accepted, but you are the first one who commented on even a small change request in a month :)

**Comment by traylenator** [comment]
This a lot cleaner I think - I have not executed this once of course.

```puppet
define yum::versionlock (
  Enum['present', 'absent', 'exclude'] $ensure  = 'present',
  Yum::PackageName                 $version = '*',
  Yum::PackageRelease              $release = '*',
  Yum::PackageEpoch                $epoch   = 0,
  Optional[Yum::PackageArch]       $arch    = undef,
) {
  require yum::plugin::versionlock

  $line_prefix = $ensure ? {
    'exclude' => '!',
    default   => '',
  }

  case $name {
    Yum::PackageName: {
      $_arch = $arch {
        Undef   => '',
        default => ".${arch},
      }

      $_versionlock = $facts['package_provider']  {
         'yum'   => "${line_prefix}${epoch}:${name}-${version}-%{release}${arch}",
         default => "${line_prefix}${name}-${epoch}:${version}-%{release}${arch}",
      }
    }
    Yum::VersionlockString {
       if $facts['package_provider'] != 'yum' {
          fail('For non yum based systems (e.g dnf) specify package, name, version, release, arch parameters for versionlock')
       }
       $_versionlock = ${line_prefix}$name
    }
    default {
      fail("Package name must be formatted as Yum::PackageName, not \'${actual}\'. See Yum::Versionlock documentation for details.")
    }
  }

  unless $ensure == 'absent' {
    concat::fragment { "yum-versionlock-${name}":
      content => "${name}\n",
      target  => $yum::plugin::versionlock::path,
    }
  }
}

```

**Comment by vchepkov** [comment]
I think I will just close my PR and you can open yours, I like your changes better

**Comment by traylenator** [comment]
#169 added

**Pull request closed without merging**
