### PR TITLE
add AlmaLinux 9 support

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Review by bastelfreak — COMMENTED** [review]
looks good, please add alma 9 to metadata.json

**Comment by jhoblitt** [comment]
@bastelfreak Doh, this is what happens when you try to work during a zoom meeting.  AlmaLinux 9 has been added to `metadata.json`.

**Review by bastelfreak — APPROVED** [review]

**Comment by bastelfreak** [comment]
mhm is that actually backwards incompatible?

**Comment by jhoblitt** [comment]
> mhm is that actually backwards incompatible?

Probably not? I thought that the mod already claimed AlmaLinux 9 support but I think it is actually only Centos 9. I'll remove the label.

**Pull request merged**
