### PR TITLE
Add Hiera support to yum::versionlock

### PR DESCRIPTION
**Pull request by mdechiaro**
#### Pull Request (PR) description
This change adds a new parameter, versionlock_options, to manage package versionlocks in Hiera.

#### This Pull Request (PR) fixes the following issues
Add new feature for supporting Hiera with versionlock configurations.

### CODE REVIEW

**Comment by mdechiaro** [comment]
I reviewed the failed checks, and it appears they were caused by Docker rate-limiting. I pasted one of the them below.

https://travis-ci.org/github/voxpupuli/puppet-yum/jobs/766942869#L1318

**Comment by traylenator** [comment]
Maybe rerun them, it's normally a problem.

It's a useful feature for sure.

**Comment by jhoblitt** [comment]
@mdechiaro Are you planning to revive this PR? I have a profile in my site module to enable versionlock from hiera and would like to see this feature merged.

**Comment by mdechiaro** [comment]
@jhoblitt thanks for reaching out. Its been a long time since I looked at this module, however I can take a look and try to get it resolved in a few days. Also, if you have code ready to be pushed, then by all means do so and I'll close this one out.

**Comment by jhoblitt** [comment]
@mdechiaro this PR looks reasonable to me. It just needs acceptance or unit tests.

**Comment by jhoblitt** [comment]
?

**Pull request closed without merging**
