### PR TITLE
Add module data for EPEL

### PR DESCRIPTION
**Pull request by lamawithonel**
This adds the data required to enable EPEL via the `managed_yumrepos`
parameter.

### CODE REVIEW

**Comment by lamawithonel** [comment]
Do you need anything else for this?

**Comment by bastelfreak** [comment]
Hi @lamawithonel, thanks for the pullrequest. Can you please add some spec tests?

**Comment by oranenj** [comment]
@lamawithonel I think it would be useful to have a few spec tests that exercise this new data... At a minimum there needs to be a test that sets managed_repos to use the repos from that list, and asserts that it does not fail with type errors or otherwise.

**Comment by lamawithonel** [comment]
Tests were added. Do you need anything else?

**Comment by Mears148** [comment]
Are all of these new changes going to be pushed to Puppet Forge as a new release any time soon? There seems to be a lot of additional functionality at this point. If there is any way I can help, let me know. Thanks.

**Pull request merged**
