### PR TITLE
(#107) YUM update puppet task support

### LINKED ISSUE #107: feature yum update puppet task support
Hi,

Would there be an interest to accept a PR which adds a Puppet task that triggers a yum update ?
Similar like the task in the puppetlabs/puppetlabs-apt module. 

Cheers.

Steven

### PR DESCRIPTION
**Pull request by catay**
#### Pull Request (PR) description

This adds a puppet task called yum that allows to run a yum update or
upgrade through bolt.

It also has a quiet parameter to run without output.

#### This Pull Request (PR) fixes the following issues
Fixes #107

### CODE REVIEW

**Comment by catay** [comment]
It seems the first 3 tests hit issue bundler/bundler#6629 .
The 4th one needs fixing on my end.

**Comment by bastelfreak** [comment]
Hi, thanks for the PR! Can you please rebase against our latest master after https://github.com/voxpupuli/puppet-yum/pull/109 got merged? That should fix the travis failures.

**Comment by catay** [comment]
All green ! Thanks.

**Comment by bastelfreak** [comment]
Thanks!

**Pull request merged**
