### PR TITLE
Re-add purge_unmanaged_repos to work properly

### PR DESCRIPTION
**Pull request by siegy22**
See https://github.com/voxpupuli/puppet-yum/pull/287#issuecomment-1407489306
and https://gist.github.com/vrillusions/7cb35a183beec5c787ba

### CODE REVIEW

**Comment by siegy22** [comment]
@kenyon Can you help me out with the tests on this? Can't get the test suite  to run locally, I have issues installing `net-telnet` when running `bundle install`.. Also I have no idea what rspec assertion to use 🤷

**Comment by kenyon** [comment]
Post the errors you're getting here and maybe we can help. But note that the tests are run by GitHub, so you can see the failures here and work on fixing them even without running the tests locally.

**Comment by siegy22** [comment]
I got it up and running locally, but still don't know what and how to assert in this test suite 😞

**Comment by trefzer** [comment]
The validation fails can also be seen on the tab 'Files changed'. I commented them as well to make it easier for you.

**Pull request closed without merging**
