### PR TITLE
Update for Puppet 4, remove support for Puppet 3

### PR DESCRIPTION
**Pull request by lamawithonel**
This commit updates the module to better utilize the features of Puppet
4.  In so doing, it removes support for older versions of Puppet.
Namely, this commit makes the following changes:

 * Adds spec tests for most components.
 * Use Puppet 4 type hinting for all parameter lists
 * Remove the params class, move static defaults, and configure
    in-module Hiera data for automatic parameter lookup.

### CODE REVIEW

**Comment by rnelson0** [comment]
Thank you! This is exciting, I think it's the first VP module to drop puppet 3 support!

You will need to update metadata.json and .travis.yml to remove Puppet 3 support. Please put the travis settings in a separate commit as this would likely be the prototype for a modulesync_configs update.

There are also some rubocop failures that need remediated.

**Comment by rnelson0** [comment]
Note: Before merging, a `puppet3` branch should be created.

**Comment by rnelson0** [comment]
@lamawithonel bump. Can I do anything to help you here?

**Comment by lamawithonel** [comment]
Yes, I've fixed the Rubocop stuff. Spotted a few things I missed and I'm working on those now.

**Comment by bastelfreak** [comment]
hey @lamawithonel, thanks for the awesome PR. Can you please rebase against master? We turned it puppet4 only now, this will shrink the travis matrix. Also we pushed an update to our rubocop conf which should lower the failures in this PR. Do you know that rubocop has an autofix option which sometimes/often works? Let us know if you need any help.

```shell
bundle exec rubocop -c .rubocop.yml -D -S -a
```

**Comment by bastelfreak** [comment]
thanks!

**Pull request merged**
