### PR TITLE
manage $repodir only if $purge_unmanaged_repos is enabled

### PR DESCRIPTION
**Pull request by vchepkov**

### CODE REVIEW

**Comment by alexjfisher** [comment]
@vchepkov I'm happy with this, but do you want to explain the context for this change?

**Comment by vchepkov** [comment]
Managing this directory introduces dependency loops for some implementation and will create issues for those who use yumrepo resources, instead of regular files. This makes this logic optional

**Review by alexjfisher — APPROVED** [review]

**Review by jhoblitt — APPROVED** [review]

**Review by bastelfreak — APPROVED** [review]

**Comment by jcpunk** [comment]
Should there be a new release with this change so folks get the fix right away?

**Comment by bastelfreak** [comment]
https://github.com/voxpupuli/puppet-yum/pull/272

**Pull request merged**
